services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracullus_web
    ports:
      - '8334:8334'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin-postgres
      POSTGRES_DB: oracullus_db
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - oracullus_net

networks:
  oracullus_net:
    external: true
